-- Справочник марок
DROP TABLE IF EXISTS vehicle_brands CASCADE;
CREATE TABLE vehicle_brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

-- Справочник моделей
DROP TABLE IF EXISTS vehicle_models CASCADE;
CREATE TABLE vehicle_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT NOT NULL REFERENCES vehicle_brands(id),
    name VARCHAR(255) NOT NULL,
    UNIQUE(brand_id, name)
);

-- Клиенты
DROP TABLE IF EXISTS clients CASCADE;
CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    phone VARCHAR(50),
    email VARCHAR(255) NOT NULL UNIQUE,
    encrypt_password VARCHAR(255) NOT NULL,
    birthday DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Транспортные средства (единая таблица для всех типов)
DROP TABLE IF EXISTS vehicles CASCADE;
CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id),
    model_id BIGINT NOT NULL REFERENCES vehicle_models(id),
    type VARCHAR(50) NOT NULL, -- 'CAR' или 'MOTORCYCLE'
    license_plate VARCHAR(50),
    vin VARCHAR(17),
    year INTEGER,
    -- Специфичные поля (nullable, заполняются только для своего типа)
    number_of_doors INTEGER,
    body_type VARCHAR(50),
    engine_capacity INTEGER,
    category VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);